import type { EnumName, TableName } from "@/lib/database.types";
import { formatLabel } from "@/lib/utils";

export type FieldType =
  | "id"
  | "text"
  | "dotSeparated"
  | "number"
  | "boolean"
  | "textarea"
  | "enum"
  | "foreignKey"
  | "timestamp";

export type ForeignKeyRef = {
  table: TableName;
  displayColumn: string;
  /** Composite label for complex parent rows */
  labelKind?: "manifestation";
  /** Filter options to rows where column equals the named form field value */
  filterBy?: { column: string; formField: string };
};

export type FieldConfig = {
  name: string;
  label: string;
  type: FieldType;
  enumName?: EnumName;
  foreignKey?: ForeignKeyRef;
  /** Hide from create/edit forms */
  formHidden?: boolean;
  /** Hide from list table */
  listHidden?: boolean;
  /** Database generates on insert (omit from create forms) */
  autoGenerated?: boolean;
  /** Populated at read time, not stored on the table */
  computed?: boolean;
  required?: boolean;
  defaultValue?: string | number | boolean | null;
  /** Allow click-to-edit directly in the list table */
  inlineEditable?: boolean;
};

export type ChildTableConfig = {
  table: TableName;
  label: string;
  /** Parent column whose value is copied into this FK on child rows */
  parentKeyColumn: string;
  /** Child FK column that receives the parent key */
  foreignKeyColumn: string;
  fields: FieldConfig[];
};

export type TableConfig = {
  name: TableName;
  label: string;
  description: string;
  /** Column used when this table appears in FK dropdowns */
  displayColumn: string;
  softDelete: boolean;
  /** Order in sidebar (lower = higher) */
  order: number;
  /** Omit from sidebar navigation (managed via a parent table form) */
  sidebarHidden?: boolean;
  /** Child rows edited inline on this table's create/edit form */
  childTables?: ChildTableConfig[];
  uniqueConstraints?: {
    fields: string[];
    ignoreDeleted?: boolean;
    message?: string;
  }[];
  /** Optional alternate list layouts (default: table only) */
  listViews?: {
    tree?: { pathField: string };
  };
  fields: FieldConfig[];
};

const timestampFields = (
  includeDeleted = true,
): FieldConfig[] => [
  {
    name: "created_at",
    label: "Created At",
    type: "timestamp",
    formHidden: true,
    listHidden: true,
  },
  {
    name: "updated_at",
    label: "Updated At",
    type: "timestamp",
    formHidden: true,
    listHidden: true,
  },
  ...(includeDeleted
    ? [
        {
          name: "deleted_at",
          label: "Deleted At",
          type: "timestamp" as const,
          formHidden: true,
          listHidden: true,
        },
      ]
    : []),
];

export const TABLE_CONFIGS: TableConfig[] = [
  {
    name: "tag",
    label: "Tags",
    description: "Core tag definitions used across interactions and demands.",
    displayColumn: "tag_name",
    softDelete: true,
    order: 1,
    listViews: {
      tree: { pathField: "tag_name" },
    },
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      { name: "tag_name", label: "Tag Name", type: "dotSeparated", required: true },
      {
        name: "layer",
        label: "Layer",
        type: "enum",
        enumName: "layer",
        inlineEditable: true,
      },
      ...timestampFields(),
    ],
  },
  {
    name: "awakener",
    label: "Awakeners",
    description: "Character stats and realm assignments.",
    displayColumn: "name",
    softDelete: true,
    order: 2,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "enlightenment",
        label: "Enlightenment",
        type: "number",
        inlineEditable: true,
      },
      { name: "realm", label: "Realm", type: "enum", enumName: "realm" },
      { name: "con", label: "CON", type: "number" },
      { name: "atk", label: "ATK", type: "number" },
      { name: "def", label: "DEF", type: "number" },
      { name: "skey", label: "SKEY", type: "number" },
      { name: "damage_amp", label: "Damage Amp", type: "number" },
      { name: "crit_rate", label: "Crit Rate", type: "number" },
      { name: "crit_dmg", label: "Crit Damage", type: "number" },
      { name: "realm_mastery", label: "Realm Mastery", type: "number" },
      { name: "aliemus_regen", label: "Aliemus Regen", type: "number" },
      { name: "sigil_yield", label: "Sigil Yield", type: "number" },
      { name: "death_resist", label: "Death Resist", type: "number" },
      ...timestampFields(),
    ],
  },
  {
    name: "desire",
    label: "Desires",
    description: "Team desire definitions for path planning.",
    displayColumn: "name",
    softDelete: true,
    order: 3,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "desire_type",
        label: "Desire Type",
        type: "enum",
        enumName: "desire_type",
        inlineEditable: true,
      },
      {
        name: "anchored_awakener_count",
        label: "Anchored Awakeners",
        type: "number",
        formHidden: true,
        computed: true,
      },
      ...timestampFields(),
    ],
    childTables: [
      {
        table: "desire_anchored_awakener",
        label: "Anchored Awakeners",
        parentKeyColumn: "id",
        foreignKeyColumn: "desire_id",
        fields: [
          {
            name: "awakener_id",
            label: "Awakener",
            type: "foreignKey",
            required: true,
            foreignKey: { table: "awakener", displayColumn: "name" },
          },
        ],
      },
    ],
  },
  {
    name: "desire_template",
    label: "Desire Templates",
    description:
      "Team loadout presets linked to a desire (posse, awakeners, wheels, covenants).",
    displayColumn: "id",
    softDelete: true,
    order: 4,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "desire_id",
        label: "Desire",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "desire", displayColumn: "name" },
      },
      {
        name: "posse_id",
        label: "Posse",
        type: "foreignKey",
        foreignKey: { table: "posse", displayColumn: "name" },
      },
      ...([1, 2, 3, 4] as const).flatMap((slot) => [
        {
          name: `slot${slot}_awakener_id`,
          label: `Slot ${slot} Awakener`,
          type: "foreignKey" as const,
          listHidden: true,
          foreignKey: { table: "awakener" as const, displayColumn: "name" },
        },
        {
          name: `slot${slot}_wheel1_id`,
          label: `Slot ${slot} Wheel 1`,
          type: "foreignKey" as const,
          listHidden: true,
          foreignKey: { table: "wheel" as const, displayColumn: "name" },
        },
        {
          name: `slot${slot}_wheel2_id`,
          label: `Slot ${slot} Wheel 2`,
          type: "foreignKey" as const,
          listHidden: true,
          foreignKey: { table: "wheel" as const, displayColumn: "name" },
        },
        {
          name: `slot${slot}_covenant_id`,
          label: `Slot ${slot} Covenant`,
          type: "foreignKey" as const,
          listHidden: true,
          foreignKey: { table: "covenant" as const, displayColumn: "name" },
        },
      ]),
      ...timestampFields(),
    ],
  },
  {
    name: "awakener_tag_manifestation",
    label: "Awakener Manifestations",
    description: "Awakener–tag pairings with graded values and requirements.",
    displayColumn: "id",
    softDelete: true,
    order: 4,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "awakener_id",
        label: "Awakener",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "awakener", displayColumn: "name" },
      },
      {
        name: "tag_id",
        label: "Tag",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "tag", displayColumn: "tag_name" },
      },
      {
        name: "override_count",
        label: "Overrides",
        type: "number",
        formHidden: true,
        computed: true,
      },
      { name: "metadata", label: "Metadata", type: "textarea" },
      {
        name: "replaces_manifestation_id",
        label: "Replaces Manifestation",
        type: "foreignKey",
        foreignKey: {
          table: "awakener_tag_manifestation",
          displayColumn: "metadata",
          filterBy: { column: "awakener_id", formField: "awakener_id" },
        },
      },
      {
        name: "dependency_stat",
        label: "Dependency Stat",
        type: "enum",
        enumName: "awakener_stat",
        inlineEditable: true,
      },
      {
        name: "value_scalar",
        label: "Value Scalar",
        type: "number",
        inlineEditable: true,
      },
      {
        name: "base_hits",
        label: "Base Hits",
        type: "number",
        inlineEditable: true,
      },
      {
        name: "is_accumulating",
        label: "Is Accumulating",
        type: "boolean",
        defaultValue: false,
        inlineEditable: true,
      },
      {
        name: "required_enlightenment",
        label: "Required Enlightenment",
        type: "number",
        defaultValue: 0,
        inlineEditable: true,
      },
      {
        name: "required_realm",
        label: "Required Realm",
        type: "enum",
        enumName: "realm",
        inlineEditable: true,
      },
      {
        name: "source_type",
        label: "Source Type",
        type: "enum",
        enumName: "source_type",
        inlineEditable: true,
      },
      {
        name: "target_type",
        label: "Target Type",
        type: "enum",
        enumName: "target_type",
        inlineEditable: true,
      },
      {
        name: "buff_target_type_restriction",
        label: "Buff Restriction",
        type: "enum",
        enumName: "source_type",
        inlineEditable: true,
      },
      ...timestampFields(),
    ],
    childTables: [
      {
        table: "manifestation_interaction_override",
        label: "Interaction Overrides",
        parentKeyColumn: "id",
        foreignKeyColumn: "manifestation_id",
        fields: [
          {
            name: "modifier_tag_id",
            label: "Modifier Tag",
            type: "foreignKey",
            foreignKey: { table: "tag", displayColumn: "tag_name" },
          },
          {
            name: "math_operation",
            label: "Math Operation",
            type: "enum",
            enumName: "operation_type",
          },
          {
            name: "override_default_factor",
            label: "Override Default Factor",
            type: "number",
          },
          {
            name: "target_type",
            label: "Target Type",
            type: "enum",
            enumName: "target_type",
          },
          {
            name: "dependency_stat",
            label: "Dependency Stat",
            type: "enum",
            enumName: "awakener_stat",
          },
          { name: "is_disabled", label: "Disabled", type: "boolean" },
        ],
      },
    ],
  },
  {
    name: "tag_default_interaction",
    label: "Tag Interactions",
    description: "Default interaction rules between modifier and target tags.",
    displayColumn: "id",
    softDelete: true,
    order: 5,
    uniqueConstraints: [
      {
        fields: ["modifier_tag_id", "target_tag_id", "source_type"],
        ignoreDeleted: true,
        message:
          "An active interaction with this modifier tag, target tag, and source type already exists.",
      },
    ],
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "modifier_tag_id",
        label: "Modifier Tag",
        type: "foreignKey",
        foreignKey: { table: "tag", displayColumn: "tag_name" },
        required: true,
      },
      {
        name: "target_tag_id",
        label: "Target Tag",
        type: "foreignKey",
        foreignKey: { table: "tag", displayColumn: "tag_name" },
        required: true,
      },
      {
        name: "exclusion_suffix",
        label: "Exclude Tag",
        type: "foreignKey",
        foreignKey: { table: "tag", displayColumn: "tag_name" },
      },
      {
        name: "math_operation",
        label: "Math Operation",
        type: "enum",
        enumName: "operation_type",
        required: true,
        inlineEditable: true,
      },
      {
        name: "default_factor",
        label: "Default Factor",
        type: "number",
        inlineEditable: true,
      },
      {
        name: "source_type",
        label: "Source Type",
        type: "enum",
        enumName: "source_type",
        inlineEditable: true,
      },
      ...timestampFields(),
    ],
  },
  {
    name: "manifestation_interaction_override",
    label: "Interaction Overrides",
    description: "Per-manifestation overrides for tag synergy math.",
    displayColumn: "id",
    softDelete: true,
    order: 6,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "manifestation_id",
        label: "Manifestation",
        type: "foreignKey",
        foreignKey: {
          table: "awakener_tag_manifestation",
          displayColumn: "id",
          labelKind: "manifestation",
        },
      },
      {
        name: "modifier_tag_id",
        label: "Modifier Tag",
        type: "foreignKey",
        foreignKey: { table: "tag", displayColumn: "tag_name" },
      },
      {
        name: "math_operation",
        label: "Math Operation",
        type: "enum",
        enumName: "operation_type",
      },
      {
        name: "override_default_factor",
        label: "Override Default Factor",
        type: "number",
      },
       {
        name: "target_type",
        label: "Target Type",
        type: "enum",
        enumName: "target_type",
      },
      {
        name: "dependency_stat",
        label: "Dependency Stat",
        type: "enum",
        enumName: "awakener_stat",
      },
      { name: "is_disabled", label: "Disabled", type: "boolean" },
      ...timestampFields(),
    ],
  },
  {
    name: "desire_demand",
    label: "Desire Demands",
    description: "Tag demand curves tied to a desire.",
    displayColumn: "id",
    softDelete: true,
    order: 7,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "desire_id",
        label: "Desire",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "desire", displayColumn: "name" },
      },
      {
        name: "tag_id",
        label: "Tag",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "tag", displayColumn: "tag_name" },
      },
      {
        name: "base_priority_weight",
        label: "Base Priority Weight",
        type: "number",
      },
      { name: "target_value", label: "Target Value", type: "number" },
      {
        name: "curve",
        label: "Curve",
        type: "enum",
        enumName: "curve_type",
      },
      { name: "decay_rate", label: "Decay Rate", type: "number" },
      ...timestampFields(),
    ],
  },
  {
    name: "path",
    label: "Paths",
    description: "Links between an awakener and a desire.",
    displayColumn: "id",
    softDelete: false,
    order: 8,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "awakener_id",
        label: "Awakener",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "awakener", displayColumn: "name" },
      },
      {
        name: "desire_id",
        label: "Desire",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "desire", displayColumn: "name" },
      },
    ],
  },
  {
    name: "desire_anchored_awakener",
    label: "Anchored Awakeners",
    description: "Awakeners anchored to a specific desire.",
    displayColumn: "id",
    softDelete: true,
    order: 9,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "desire_id",
        label: "Desire",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "desire", displayColumn: "name" },
      },
      {
        name: "awakener_id",
        label: "Awakener",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "awakener", displayColumn: "name" },
      },
      ...timestampFields(),
    ],
  },
  {
    name: "posse",
    label: "Posse",
    description: "Posse definitions for team loadouts.",
    displayColumn: "name",
    softDelete: true,
    order: 10,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      { name: "name", label: "Name", type: "text", required: true },
      ...timestampFields(),
    ],
  },
  {
    name: "posse_tag_manifestation",
    label: "Posse Manifestations",
    description: "Posse–tag pairings with requirements and values.",
    displayColumn: "id",
    softDelete: true,
    order: 11,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "posse_id",
        label: "Posse",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "posse", displayColumn: "name" },
      },
      {
        name: "tag_id",
        label: "Tag",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "tag", displayColumn: "tag_name" },
      },
      {
        name: "required_awakener",
        label: "Required Awakener",
        type: "foreignKey",
        foreignKey: { table: "awakener", displayColumn: "name" },
      },
      {
        name: "required_realm",
        label: "Required Realm",
        type: "enum",
        enumName: "realm",
        inlineEditable: true,
      },
      {
        name: "target_type",
        label: "Target Type",
        type: "enum",
        enumName: "target_type",
        inlineEditable: true,
      },
      {
        name: "value_scalar",
        label: "Value Scalar",
        type: "number",
        inlineEditable: true,
      },
      {
        name: "is_accumulating",
        label: "Is Accumulating",
        type: "boolean",
        defaultValue: false,
        inlineEditable: true,
      },
      { name: "metadata", label: "Metadata", type: "textarea" },
      ...timestampFields(),
    ],
  },
  {
    name: "wheel",
    label: "Wheels",
    description: "Wheel gear with rarity and stat bonuses.",
    displayColumn: "name",
    softDelete: true,
    order: 12,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "enlightenment",
        label: "Enlightenment",
        type: "number",
        inlineEditable: true,
      },
      {
        name: "rarity",
        label: "Rarity",
        type: "enum",
        enumName: "rarity",
        inlineEditable: true,
      },
      {
        name: "stat",
        label: "Stat",
        type: "enum",
        enumName: "awakener_stat",
        inlineEditable: true,
      },
      { name: "stat_amount", label: "Stat Amount", type: "number", inlineEditable: true },
      ...timestampFields(),
    ],
  },
  {
    name: "wheel_tag_manifestation",
    label: "Wheel Manifestations",
    description: "Wheel–tag pairings with graded values and requirements.",
    displayColumn: "id",
    softDelete: true,
    order: 13,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "wheel_id",
        label: "Wheel",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "wheel", displayColumn: "name" },
      },
      {
        name: "tag_id",
        label: "Tag",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "tag", displayColumn: "tag_name" },
      },
      {
        name: "dependency_stat",
        label: "Dependency Stat",
        type: "enum",
        enumName: "awakener_stat",
        inlineEditable: true,
      },
      {
        name: "buff_target_type_restriction",
        label: "Buff Restriction",
        type: "enum",
        enumName: "source_type",
        inlineEditable: true,
      },
      {
        name: "required_realm",
        label: "Required Realm",
        type: "enum",
        enumName: "realm",
        inlineEditable: true,
      },
      {
        name: "target_type",
        label: "Target Type",
        type: "enum",
        enumName: "target_type",
        inlineEditable: true,
      },
      {
        name: "value_scalar",
        label: "Value Scalar",
        type: "number",
        inlineEditable: true,
      },
      {
        name: "is_accumulating",
        label: "Is Accumulating",
        type: "boolean",
        defaultValue: false,
        inlineEditable: true,
      },
      { name: "metadata", label: "Metadata", type: "textarea" },
      ...timestampFields(),
    ],
  },
  {
    name: "covenant",
    label: "Covenants",
    description: "Covenant gear with stat bonuses.",
    displayColumn: "name",
    softDelete: true,
    order: 14,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "stat",
        label: "Stat",
        type: "enum",
        enumName: "awakener_stat",
        inlineEditable: true,
      },
      { name: "stat_amount", label: "Stat Amount", type: "number", inlineEditable: true },
      ...timestampFields(),
    ],
  },
  {
    name: "covenant_tag_manifestation",
    label: "Covenant Manifestations",
    description: "Covenant–tag pairings with graded values and requirements.",
    displayColumn: "id",
    softDelete: true,
    order: 15,
    fields: [
      { name: "id", label: "ID", type: "id", autoGenerated: true, formHidden: true },
      {
        name: "covenant_id",
        label: "Covenant",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "covenant", displayColumn: "name" },
      },
      {
        name: "tag_id",
        label: "Tag",
        type: "foreignKey",
        required: true,
        foreignKey: { table: "tag", displayColumn: "tag_name" },
      },
      {
        name: "replaces_manifestation_id",
        label: "Replaces Manifestation",
        type: "foreignKey",
        foreignKey: {
          table: "covenant_tag_manifestation",
          displayColumn: "metadata",
          filterBy: { column: "covenant_id", formField: "covenant_id" },
        },
      },
      {
        name: "is_accumulating",
        label: "Is Accumulating",
        type: "boolean",
        defaultValue: false,
        inlineEditable: true,
      },
      {
        name: "required_realm",
        label: "Required Realm",
        type: "enum",
        enumName: "realm",
        inlineEditable: true,
      },
      {
        name: "target_type",
        label: "Target Type",
        type: "enum",
        enumName: "target_type",
        inlineEditable: true,
      },
      {
        name: "value_scalar",
        label: "Value Scalar",
        type: "number",
        inlineEditable: true,
      },
      { name: "metadata", label: "Metadata", type: "textarea" },
      ...timestampFields(),
    ],
  },
];

export const TABLE_CONFIG_MAP = Object.fromEntries(
  TABLE_CONFIGS.map((config) => [config.name, config]),
) as Record<TableName, TableConfig>;

export type SidebarNavGroup = {
  label: string;
  tables: TableName[];
};

export const SIDEBAR_NAV_GROUPS: SidebarNavGroup[] = [
  { label: "Tags", tables: ["tag", "tag_default_interaction"] },
  { label: "Awakeners", tables: ["awakener", "awakener_tag_manifestation", "manifestation_interaction_override"] },
  { label: "Wheels", tables: ["wheel", "wheel_tag_manifestation"] },
  { label: "Covenants", tables: ["covenant", "covenant_tag_manifestation"] },
  { label: "Posse", tables: ["posse", "posse_tag_manifestation"] },
  { label: "Desires", tables: ["path", "desire", "desire_template", "desire_demand", "desire_anchored_awakener"] },
];

export function isValidTableName(name: string): name is TableName {
  return name in TABLE_CONFIG_MAP;
}

export function getListFields(config: TableConfig) {
  return config.fields.filter((field) => !field.listHidden);
}

export function getFormFields(config: TableConfig) {
  return config.fields.filter((field) => !field.formHidden);
}

export function getTableTitle(tableName: TableName) {
  return TABLE_CONFIG_MAP[tableName].label;
}

export function getFieldLabel(fieldName: string) {
  return formatLabel(fieldName);
}
