CREATE TYPE public.desire_type AS ENUM ('general', 'specific');

ALTER TABLE public.desire
  ADD COLUMN description text,
  ADD COLUMN desire_type public.desire_type;

CREATE TABLE public.desire_anchored_awakener (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  awakener_id integer NOT NULL,
  desire_id integer NOT NULL,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone
);

ALTER TABLE public.desire_anchored_awakener OWNER TO postgres;

ALTER TABLE ONLY public.desire_anchored_awakener
  ADD CONSTRAINT desire_anchored_awakener_awakener_id_fkey
  FOREIGN KEY (awakener_id) REFERENCES public.awakener (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_anchored_awakener
  ADD CONSTRAINT desire_anchored_awakener_desire_id_fkey
  FOREIGN KEY (desire_id) REFERENCES public.desire (id) DEFERRABLE;

ALTER TABLE public.desire_anchored_awakener ENABLE ROW LEVEL SECURITY;

GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.desire_anchored_awakener TO anon;
GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.desire_anchored_awakener TO authenticated;
GRANT ALL ON TABLE public.desire_anchored_awakener TO service_role;
