-- Seed public.relic_tag_manifestation from the Astral Reign Gold/Cursed relic research
-- (supabase/migrations/relic_astral_reign_research_9f2c4b71.plan.md).
-- Rows are keyed by relic name + tag_name so no numeric IDs are hardcoded.
--
-- Encoding:
--   fixed    -> kind='fixed',    value_scalar = literal (percentages as fractions)
--   computed -> kind='computed', base_formula = SKeyDB formula, value_scalar = multiplier
-- trigger_condition only reuses existing Special.When.Posse / Special.When.Devour tags;
-- all other conditions are recorded in metadata.

WITH rows(
  relic_name, tag_name, value_scalar, target_type, kind, base_formula,
  is_accumulating, is_permanent, trigger_tag, dependency_stat, metadata
) AS (
  VALUES
    -- Astral Reign - Gold
    ('Alfonso''s Artifact', 'Support.Create.Insight', '2', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Place 2 Insight cards in hand'),
    ('Arcana Archive', 'Attacker.Counter', '0.12', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'Play 2 rising-cost cards'),
    ('Arcana Relic', 'Attacker.Poison', '0.24', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'Play 2 falling-cost cards'),
    ('Arcane Gloves', 'Support.Draw', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Draw 2 when hand <= 3'),
    ('Blessed Blood', 'Defender.Heal', '0.1', 'aoe', 'computed', 'esotericResearchDepth', 'true', 'false', NULL, NULL, 'At turn end'),
    ('Bloody Pebble', 'Attacker.Bleed Trigger', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, '30% of Active DMG as Bleed'),
    ('Brand-New Wallet', 'Support.Draw', '4', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Brand-New Wallet', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Celestial Astrolabe', 'Support.Base Damage', '0.2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Celestial Astrolabe', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Chant of the Tides', 'Support.Generate Permanent Tentacle', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Battle start'),
    ('Chronometric Device', 'Support.Keyflare', '500', 'single', 'fixed', NULL, 'false', 'false', 'Special.When.Posse', NULL, 'Second Posse each turn'),
    ('Chronometric Device', 'Support.Aliemus', '10', 'aoe', 'fixed', NULL, 'false', 'false', 'Special.When.Posse', NULL, 'Second Posse each turn'),
    ('Crimson Brooch', 'Support.STR Up', '0.1', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'Battle start'),
    ('Dearest Babe', 'Support.Crimson Furnace', '0.075', 'single', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'On Embryo generated'),
    ('Deceased''s Chrono', 'Attacker.Counter', '0.35', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'When Defense played'),
    ('Differential Engine', 'Support.Arithmetica', '6', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Exalt 4 times'),
    ('Doctor''s Case', 'Support.Damage AMP', '0.5', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start, HP<50%'),
    ('Doctor''s Case', 'Support.Draw', '2', 'single', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start, HP<25%'),
    ('Doctor''s Case', 'Support.Arithmetica', '2', 'single', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start, HP<25%'),
    ('Easter Moment', 'Support.Aliemus', '20', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start'),
    ('Filigree Agate', 'Support.STR Up', '0.015', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'On DMG dealt, up to 15/turn'),
    ('Fleeting Beauty', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'On Exalt'),
    ('Foreign Stamp Album', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Forgotten Loom', 'Support.Realm Mastery', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After battle starts'),
    ('Forgotten Loom', 'Support.Increase Gain.Poison', '0.2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Awakener and Relic Poison effects +20%'),
    ('Forgotten Prelude', 'Attacker.Counter', '0.3', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'Keyflare Rouse'),
    ('Forgotten Prelude', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Keyflare Rouse'),
    ('Forsaken Blood', 'Support.Base Damage', '0.2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'All Awakeners'),
    ('Forsaken Blood', 'Support.Base Damage', '0.5', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Temporary before Exalt'),
    ('Gilded Reverie', 'Support.Aliemus', '20', 'aoe', 'fixed', NULL, 'false', 'false', 'Special.When.Devour', NULL, 'First Devour each turn'),
    ('Guardian Hand', 'Defender.Shield', '0.25', 'aoe', 'computed', 'esotericResearchDepth', 'true', 'false', NULL, NULL, 'At turn start, HP<25%'),
    ('Harford''s Elixir', 'Support.Damage AMP', '0.5', 'aoe', 'fixed', NULL, 'false', 'false', 'Special.When.Posse', NULL, 'First Posse each turn'),
    ('Hierophant''s Staff', 'Support.Damage AMP', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Battle start'),
    ('Hierophant''s Staff', 'Attacker.Poison', '0.06', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'Up to 5/turn'),
    ('Highest Honor', 'Support.STR Up', '0.22', 'aoe', 'computed', 'esotericResearchDepth', 'true', 'false', NULL, NULL, 'At turn start, HP<25%'),
    ('Hyperstring Pocketwatch', 'Defender.Shield', '0.4', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'From Annihilation, 3-turn CD'),
    ('Iron Lock', 'Support.STR Up', '0.0625', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'After Exalt'),
    ('Kaleidoscope', 'Support.Damage AMP', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Battle start'),
    ('Kaleidoscope', 'Support.Damage AMP', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Per Command Card by different Awakener'),
    ('Laurel Cufflinks', 'Support.Aliemus', '20', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Laurel Cufflinks', 'Support.Keyflare', '200', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Lemurian Delight', 'Special.All Tentacle Attack', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Raging Waves stance, 3-turn CD'),
    ('Lucky Rabbit''s Paw', 'Support.Keyflare', '0.5', 'single', 'fixed', NULL, 'false', 'false', 'Special.When.Posse', NULL, 'Refund 50% of consumed Keyflare'),
    ('Luminous Hourglass', 'Support.Additional Instance', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'First non-derived Command Card after Ultra Round'),
    ('Malignant Child', 'Defender.Debuff.Weakness', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After battle starts, doubled in Boss'),
    ('Malignant Child', 'Support.Base Damage', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'All Awakeners'),
    ('Mythag Insignia', 'Support.Arithmetica', '4', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Mythag Insignia', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Nameless Appendage', 'Defender.STR Down', '0.16', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'Tranquil Sea stance, 3-turn CD'),
    ('Nettle Vest', 'Attacker.Counter', '0.4', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'Battle start, doubled in Boss'),
    ('Neurotoxin', 'Attacker.Poison', '0.8', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'Battle start, doubled in Boss'),
    ('Other Tongue', 'Attacker.Poison Trigger', '0.2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Strike poison equal to 20% DMG'),
    ('Our Home', 'Support.STR Up', '0.05', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'Keyflare Rouse'),
    ('Our Home', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Keyflare Rouse'),
    ('Phantom Hand', 'Defender.STR Down', '0.12', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'Battle start; Crimson Furnace 3-turn CD'),
    ('Plague Record', 'Support.Increase Gain.Embryo Fusion', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Embryo Fusion automatic gain +200%'),
    ('Preserved Butterfly', 'Defender.Shield', '0.3', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Preserved Butterfly', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Prophet''s Lamp', 'Attacker.Poison', '0.15', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', 'Special.When.Posse', NULL, 'First Posse each turn'),
    ('Prophet''s Lamp', 'Attacker.Counter', '0.075', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', 'Special.When.Posse', NULL, 'First Posse each turn'),
    ('Proto Battery', 'Support.Aliemus', '10', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start'),
    ('Putney Morning Post', 'Support.Damage AMP', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Battle start'),
    ('Putney Morning Post', 'Support.Arithmetica', '2', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'First Counter each turn'),
    ('Radium Jawbone', 'Attacker.Active Damage.Fixed Damage', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, 'team_max_hp', 'Pure DMG = 30% team Max HP after Exalt'),
    ('Radium Jawbone', 'Attacker.Poison Trigger', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Trigger 30% Poison after Exalt'),
    ('Relic of the Past', 'Support.Keyflare', '1000', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Battle start and after Death Resistance'),
    ('Rhind Papyrus', 'Support.Damage AMP', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Battle start'),
    ('Rhind Papyrus', 'Support.Draw', '2', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'First Poison each turn'),
    ('Rite of Spring', 'Support.Debuff.Vulnerability', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After battle starts, doubled in Boss'),
    ('Rite of Spring', 'Support.Base Damage', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'All Awakeners'),
    ('Ritual Dagger', 'Attacker.Active Damage.Fixed Damage', '0.5', 'aoe', 'fixed', NULL, 'false', 'false', NULL, 'team_max_hp', 'Pure DMG = 50% team Max HP when attacked'),
    ('Rusted Saw', 'Support.Crimson Furnace', '0.2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, '20% of HP loss on losing HP'),
    ('Rusty Lancet', 'Attacker.Active Damage.Strike', '0.6', 'aoe', 'fixed', NULL, 'false', 'false', NULL, 'atk', 'Extra Strike = 60% ATK, 2 more times'),
    ('Safe Passage', 'Support.Damage AMP', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Battle start'),
    ('Safe Passage', 'Attacker.Counter', '0.06', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'After taking damage, up to 3/turn'),
    ('Serpent''s Husk', 'Support.Increase Gain.Heal', '0.2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'HP Recovery base effect +20%'),
    ('Serpent''s Husk', 'Support.Increase Gain.Shield', '0.2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Shield base effect +20%'),
    ('Severed Head Worm', 'Support.Tentacle Damage Up', '0.1', 'aoe', 'computed', 'esotericResearchDepth', 'true', 'false', NULL, NULL, 'At turn end in Surging Tides, 3-turn CD'),
    ('Silent Prelude', 'Support.STR Up', '0.0125', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'On draw or discard, up to 15/turn'),
    ('Silver Tongue', 'Support.Keyflare', '200', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'First Command Card each turn'),
    ('Solar Disc', 'Support.Realm Mastery', '100', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After battle starts'),
    ('Solar Disc', 'Support.Draw', '2', 'single', 'fixed', NULL, 'true', 'false', NULL, NULL, 'Start of odd turns'),
    ('Solar Disc', 'Support.Arithmetica', '2', 'single', 'fixed', NULL, 'true', 'false', NULL, NULL, 'Start of even turns'),
    ('Spatial Deflector', 'Defender.Debuff.Weakness', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Battle start; after Annihilation'),
    ('Spatial Deflector', 'Support.Debuff.Vulnerability', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Battle start; after Annihilation'),
    ('Stellar Brew', 'Support.Take Effect Again', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After 5 Exalts'),
    ('Submersible Helm', 'Support.Debuff.Tentacle Vulnerability', '0.02', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After active or Tentacle DMG, up to 20/turn'),
    ('Tilted Scales', 'Support.Aliemus', '6', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'Before turn end'),
    ('Time Scarab', 'Support.Aliemus', '100', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Annihilation, 3-turn CD'),
    ('Tiny Music Box', 'Support.STR Up', '0.07', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'Battle start'),
    ('Tiny Music Box', 'Support.STR Up', '0.02', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'Temporary on Exhaust card, up to 10/turn'),
    ('Trigon Prism', 'Support.Draw.Command Card', '2', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Card enters Ultra Space, up to 2/turn'),
    ('True North Compass', 'Support.Draw', '2', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start'),
    ('Truth Unbound', 'Support.Realm Mastery', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After battle starts'),
    ('Truth Unbound', 'Attacker.Non-Active Damage.Counter Damage', '0.2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Awakener and Relic Counter DMG +20%'),
    ('Uncanny Salve', 'Attacker.Poison', '0.6', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'Keyflare Rouse'),
    ('Uncanny Salve', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Keyflare Rouse'),
    ('Veil of the Nameless Deity', 'Support.Aliemus', '40', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, '4 different Awakeners consecutive, 3-turn CD'),
    ('Vision Corrector', 'Support.Damage AMP', '0.3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'First five attacks each turn'),
    ('Voyager''s Parasol', 'Defender.Heal', '0.2', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Voyager''s Parasol', 'Support.Keyflare', '200', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse'),
    ('Weeping Pipe', 'Support.Base Damage', '0.6', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'All Awakeners Base DMG +60%'),
    ('Yellow Snail', 'Special.All Tentacle Attack', '2', 'aoe', 'fixed', NULL, 'false', 'false', 'Special.When.Posse', NULL, 'First Posse each turn, 50% DMG'),
    ('Yellow Snail', 'Support.Tentacle Damage Up', '0.5', 'aoe', 'fixed', NULL, 'false', 'false', 'Special.When.Posse', NULL, 'First Posse each turn, 50% DMG'),
    -- Astral Reign - Cursed
    ('Black Candle', 'Support.Base Damage', '0.5', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'All Awakeners Base DMG +50%'),
    ('Black Candle', 'Support.Base Damage', '0.1', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Per deck reset, max +100%'),
    ('Eerie Hook', 'Support.Final Damage', '0.35', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, '4 different Awakener Command Cards in a turn'),
    ('Eerie Hook', 'Support.Aliemus', '-5', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Lose 5 Aliemus'),
    ('Jade Imprint', 'Support.Create.Command Card', '1', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After Keyflare Rouse, copy into all piles'),
    ('Mind Engraving', 'Support.Aliemus', '30', 'single', 'fixed', NULL, 'false', 'false', NULL, NULL, 'Rouse card played; cost reduced to 0'),
    ('Nightmare Manifest', 'Support.Create.Insight', '1', 'single', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start if Keyflare > 500'),
    ('Omen Ritual Bird', 'Support.STR Up', '0.05', 'aoe', 'computed', 'esotericResearchDepth', 'false', 'true', NULL, NULL, 'Battle start permanent STR; converts to Temporary each turn'),
    ('Pathwalker''s Remains', 'Attacker.Counter', '0.2', 'aoe', 'computed', 'occultResearchDepth', 'true', 'false', NULL, NULL, 'At turn start; Exalt conversion, 3-turn CD'),
    ('Sacred Agony', 'Support.Generate Permanent Tentacle', '1', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start if <=1 Permanent Tentacle'),
    ('Sacred Agony', 'Support.Generate Temporary Tentacle', '3', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start if >1 Permanent Tentacle, lose 1'),
    ('Salvific Limb', 'Attacker.Poison', '0.8', 'aoe', 'computed', 'occultResearchDepth', 'false', 'false', NULL, NULL, 'Battle start'),
    ('Salvific Limb', 'Attacker.Bleed', '5', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start, convert 25% of enemy Poison'),
    ('Swarm Mind', 'Support.STR Up', '0.01', 'aoe', 'computed', 'esotericResearchDepth', 'true', 'false', NULL, NULL, 'At turn start per vacant Ultra Space'),
    ('Swarm Mind', 'Attacker.Poison', '0.005', 'single', 'computed', 'accountStageGrowth', 'true', 'false', NULL, NULL, 'At turn start, self Poison'),
    ('Trickster''s Hat', 'Support.Draw', '3', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After draw phase'),
    ('Trickster''s Hat', 'Support.Discard', '2', 'aoe', 'fixed', NULL, 'false', 'false', NULL, NULL, 'After draw phase'),
    ('Wailing Bell', 'Support.Draw', '-1', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start, draw 1 less'),
    ('Wailing Bell', 'Support.Arithmetica', '1', 'single', 'fixed', NULL, 'true', 'false', NULL, NULL, 'Per card with cost >= 3, up to 3/turn'),
    ('Wriggling Cord', 'Support.Embryo Fusion', '100', 'aoe', 'fixed', NULL, 'true', 'false', NULL, NULL, 'At turn start')
)
INSERT INTO public.relic_tag_manifestation (
  relic_id, tag_id, trigger_condition, value_scalar, target_type, kind,
  base_formula, is_accumulating, is_permanent, dependency_stat, metadata
)
SELECT
  r.id,
  t.id,
  tr.id,
  v.value_scalar::double precision,
  v.target_type::public.target_type,
  v.kind::public.relic_arg_kind,
  NULLIF(v.base_formula, '')::public.relic_base_formula,
  v.is_accumulating::boolean,
  v.is_permanent::boolean,
  NULLIF(v.dependency_stat, '')::public.all_stats,
  v.metadata
FROM rows v
JOIN public.relic r ON r.name = v.relic_name
JOIN public.tag t ON t.tag_name = v.tag_name
LEFT JOIN public.tag tr ON tr.tag_name = v.trigger_tag;
