CREATE TABLE public.desire_template (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  posse_id integer,
  slot1_awakener_id integer,
  slot1_wheel1_id integer,
  slot1_wheel2_id integer,
  slot1_covenant_id integer,
  slot2_awakener_id integer,
  slot2_wheel1_id integer,
  slot2_wheel2_id integer,
  slot2_covenant_id integer,
  slot3_awakener_id integer,
  slot3_wheel1_id integer,
  slot3_wheel2_id integer,
  slot3_covenant_id integer,
  slot4_awakener_id integer,
  slot4_wheel1_id integer,
  slot4_wheel2_id integer,
  slot4_covenant_id integer,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone,
  desire_id integer NOT NULL
);

ALTER TABLE public.desire_template OWNER TO postgres;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_desire_id_fkey
  FOREIGN KEY (desire_id) REFERENCES public.desire (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_posse_id_fkey
  FOREIGN KEY (posse_id) REFERENCES public.posse (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot1_awakener_id_fkey
  FOREIGN KEY (slot1_awakener_id) REFERENCES public.awakener (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot1_wheel1_id_fkey
  FOREIGN KEY (slot1_wheel1_id) REFERENCES public.wheel (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot1_wheel2_id_fkey
  FOREIGN KEY (slot1_wheel2_id) REFERENCES public.wheel (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot1_covenant_id_fkey
  FOREIGN KEY (slot1_covenant_id) REFERENCES public.covenant (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot2_awakener_id_fkey
  FOREIGN KEY (slot2_awakener_id) REFERENCES public.awakener (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot2_wheel1_id_fkey
  FOREIGN KEY (slot2_wheel1_id) REFERENCES public.wheel (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot2_wheel2_id_fkey
  FOREIGN KEY (slot2_wheel2_id) REFERENCES public.wheel (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot2_covenant_id_fkey
  FOREIGN KEY (slot2_covenant_id) REFERENCES public.covenant (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot3_awakener_id_fkey
  FOREIGN KEY (slot3_awakener_id) REFERENCES public.awakener (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot3_wheel1_id_fkey
  FOREIGN KEY (slot3_wheel1_id) REFERENCES public.wheel (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot3_wheel2_id_fkey
  FOREIGN KEY (slot3_wheel2_id) REFERENCES public.wheel (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot3_covenant_id_fkey
  FOREIGN KEY (slot3_covenant_id) REFERENCES public.covenant (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot4_awakener_id_fkey
  FOREIGN KEY (slot4_awakener_id) REFERENCES public.awakener (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot4_wheel1_id_fkey
  FOREIGN KEY (slot4_wheel1_id) REFERENCES public.wheel (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot4_wheel2_id_fkey
  FOREIGN KEY (slot4_wheel2_id) REFERENCES public.wheel (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot4_covenant_id_fkey
  FOREIGN KEY (slot4_covenant_id) REFERENCES public.covenant (id) DEFERRABLE;

ALTER TABLE public.desire_template ENABLE ROW LEVEL SECURITY;

GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.desire_template TO anon;
GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.desire_template TO authenticated;
GRANT ALL ON TABLE public.desire_template TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
