CREATE TABLE public.covenant_stat_set (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stat public.all_stats,
  stat_amount double precision,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone
);

ALTER TABLE public.covenant_stat_set OWNER TO postgres;

ALTER TABLE public.covenant_stat_set ENABLE ROW LEVEL SECURITY;

GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.covenant_stat_set TO anon;
GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.covenant_stat_set TO authenticated;
GRANT ALL ON TABLE public.covenant_stat_set TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

ALTER TABLE public.desire_template
  ADD COLUMN slot1_covenant_stat_set_id integer,
  ADD COLUMN slot2_covenant_stat_set_id integer,
  ADD COLUMN slot3_covenant_stat_set_id integer,
  ADD COLUMN slot4_covenant_stat_set_id integer;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot1_covenant_stat_set_id_fkey
  FOREIGN KEY (slot1_covenant_stat_set_id) REFERENCES public.covenant_stat_set (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot2_covenant_stat_set_id_fkey
  FOREIGN KEY (slot2_covenant_stat_set_id) REFERENCES public.covenant_stat_set (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot3_covenant_stat_set_id_fkey
  FOREIGN KEY (slot3_covenant_stat_set_id) REFERENCES public.covenant_stat_set (id) DEFERRABLE;

ALTER TABLE ONLY public.desire_template
  ADD CONSTRAINT desire_template_slot4_covenant_stat_set_id_fkey
  FOREIGN KEY (slot4_covenant_stat_set_id) REFERENCES public.covenant_stat_set (id) DEFERRABLE;
