-- Path Carver primary-stat bake-in (idempotent absolute SET).
-- Source: SKeyDB 3d5f0ab8b1580cc9585b44f8697dcdcebc537622
-- Assumptions:
--   Awakener level 60
--   Soulforge lv10 (clamped to talent max; 0 if absent)
--   Gnostic Potential lv0, except limited awakeners who are lv5 (SKeyDB defaultMaxed)
-- Generated by scripts/generate-awakener-primary-stats-datapatch.ts
-- Re-running is safe (absolute values, not multipliers).

-- Limited / gnostic lv5 (31): "24", Castor, Clementine, Corposant, Daffodil, Doresain, Doll: Inferno, Helot: Catena, Hameln, Horla, Kathigu-Ra, Lily, Miryam, Mouchette, Murphy, Murphy: Fauxborn, Pickman, Pollux, Ryker, Salvador, Sorel, Tawil, Thais, Tulu, Wanda, Xu, Vortice, Arachne, Saya, Pontos, Lotan: Cetarchon

-- "24" (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 194,
  atk = 246,
  def = 112,
  updated_at = NOW()
WHERE id = 3
  AND deleted_at IS NULL
  AND name = '"24"';

-- Agrippa (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 172,
  atk = 146,
  def = 177,
  updated_at = NOW()
WHERE id = 4
  AND deleted_at IS NULL
  AND name = 'Agrippa';

-- Aigis (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 130,
  atk = 156,
  def = 141,
  updated_at = NOW()
WHERE id = 5
  AND deleted_at IS NULL
  AND name = 'Aigis';

-- Alva (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 156,
  atk = 167,
  def = 182,
  updated_at = NOW()
WHERE id = 6
  AND deleted_at IS NULL
  AND name = 'Alva';

-- Aurita (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 125,
  atk = 136,
  def = 120,
  updated_at = NOW()
WHERE id = 7
  AND deleted_at IS NULL
  AND name = 'Aurita';

-- Caecus (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 203,
  atk = 162,
  def = 177,
  updated_at = NOW()
WHERE id = 8
  AND deleted_at IS NULL
  AND name = 'Caecus';

-- Casiah (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 141,
  atk = 146,
  def = 125,
  updated_at = NOW()
WHERE id = 9
  AND deleted_at IS NULL
  AND name = 'Casiah';

-- Castor (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 194,
  atk = 176,
  def = 206,
  updated_at = NOW()
WHERE id = 10
  AND deleted_at IS NULL
  AND name = 'Castor';

-- Celeste (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 104,
  atk = 99,
  def = 104,
  updated_at = NOW()
WHERE id = 11
  AND deleted_at IS NULL
  AND name = 'Celeste';

-- Clementine (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 164,
  atk = 194,
  def = 159,
  updated_at = NOW()
WHERE id = 12
  AND deleted_at IS NULL
  AND name = 'Clementine';

-- Corposant (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 188,
  atk = 164,
  def = 194,
  updated_at = NOW()
WHERE id = 13
  AND deleted_at IS NULL
  AND name = 'Corposant';

-- Daffodil (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 182,
  atk = 229,
  def = 171,
  updated_at = NOW()
WHERE id = 14
  AND deleted_at IS NULL
  AND name = 'Daffodil';

-- Doll (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 115,
  atk = 94,
  def = 125,
  updated_at = NOW()
WHERE id = 15
  AND deleted_at IS NULL
  AND name = 'Doll';

-- Doresain (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 194,
  atk = 206,
  def = 171,
  updated_at = NOW()
WHERE id = 16
  AND deleted_at IS NULL
  AND name = 'Doresain';

-- Erica (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 193,
  atk = 188,
  def = 188,
  updated_at = NOW()
WHERE id = 17
  AND deleted_at IS NULL
  AND name = 'Erica';

-- Faint (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 136,
  atk = 104,
  def = 162,
  updated_at = NOW()
WHERE id = 18
  AND deleted_at IS NULL
  AND name = 'Faint';

-- Faros (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 125,
  atk = 136,
  def = 156,
  updated_at = NOW()
WHERE id = 19
  AND deleted_at IS NULL
  AND name = 'Faros';

-- Doll: Inferno (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 129,
  atk = 106,
  def = 141,
  updated_at = NOW()
WHERE id = 20
  AND deleted_at IS NULL
  AND name = 'Doll: Inferno';

-- Helot: Catena (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 206,
  atk = 199,
  def = 147,
  updated_at = NOW()
WHERE id = 21
  AND deleted_at IS NULL
  AND name = 'Helot: Catena';

-- Ramona: Timeworn (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 156,
  atk = 156,
  def = 156,
  updated_at = NOW()
WHERE id = 22
  AND deleted_at IS NULL
  AND name = 'Ramona: Timeworn';

-- Goliath (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 214,
  atk = 208,
  def = 172,
  updated_at = NOW()
WHERE id = 23
  AND deleted_at IS NULL
  AND name = 'Goliath';

-- Hameln (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 176,
  atk = 182,
  def = 171,
  updated_at = NOW()
WHERE id = 24
  AND deleted_at IS NULL
  AND name = 'Hameln';

-- Helot (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 182,
  atk = 177,
  def = 130,
  updated_at = NOW()
WHERE id = 25
  AND deleted_at IS NULL
  AND name = 'Helot';

-- Horla (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 136,
  atk = 141,
  def = 124,
  updated_at = NOW()
WHERE id = 26
  AND deleted_at IS NULL
  AND name = 'Horla';

-- Jenkin (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 130,
  atk = 182,
  def = 136,
  updated_at = NOW()
WHERE id = 27
  AND deleted_at IS NULL
  AND name = 'Jenkin';

-- Karen (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 146,
  atk = 125,
  def = 141,
  updated_at = NOW()
WHERE id = 28
  AND deleted_at IS NULL
  AND name = 'Karen';

-- Kathigu-Ra (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 182,
  atk = 218,
  def = 164,
  updated_at = NOW()
WHERE id = 29
  AND deleted_at IS NULL
  AND name = 'Kathigu-Ra';

-- Leigh (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 94,
  atk = 94,
  def = 94,
  updated_at = NOW()
WHERE id = 30
  AND deleted_at IS NULL
  AND name = 'Leigh';

-- Lily (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 211,
  atk = 153,
  def = 211,
  updated_at = NOW()
WHERE id = 31
  AND deleted_at IS NULL
  AND name = 'Lily';

-- Liz (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 141,
  atk = 193,
  def = 151,
  updated_at = NOW()
WHERE id = 32
  AND deleted_at IS NULL
  AND name = 'Liz';

-- Lotan (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 167,
  atk = 172,
  def = 146,
  updated_at = NOW()
WHERE id = 33
  AND deleted_at IS NULL
  AND name = 'Lotan';

-- Miryam (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 124,
  atk = 194,
  def = 106,
  updated_at = NOW()
WHERE id = 34
  AND deleted_at IS NULL
  AND name = 'Miryam';

-- Mouchette (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 164,
  atk = 194,
  def = 164,
  updated_at = NOW()
WHERE id = 35
  AND deleted_at IS NULL
  AND name = 'Mouchette';

-- Murphy (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 171,
  atk = 182,
  def = 206,
  updated_at = NOW()
WHERE id = 36
  AND deleted_at IS NULL
  AND name = 'Murphy';

-- Murphy: Fauxborn (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 129,
  atk = 159,
  def = 153,
  updated_at = NOW()
WHERE id = 37
  AND deleted_at IS NULL
  AND name = 'Murphy: Fauxborn';

-- Nautila (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 198,
  atk = 120,
  def = 208,
  updated_at = NOW()
WHERE id = 38
  AND deleted_at IS NULL
  AND name = 'Nautila';

-- Nymphaea (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 99,
  atk = 156,
  def = 104,
  updated_at = NOW()
WHERE id = 39
  AND deleted_at IS NULL
  AND name = 'Nymphaea';

-- Ogier (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 177,
  atk = 151,
  def = 193,
  updated_at = NOW()
WHERE id = 40
  AND deleted_at IS NULL
  AND name = 'Ogier';

-- Pandia (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 156,
  atk = 182,
  def = 162,
  updated_at = NOW()
WHERE id = 41
  AND deleted_at IS NULL
  AND name = 'Pandia';

-- Pickman (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 188,
  atk = 171,
  def = 188,
  updated_at = NOW()
WHERE id = 42
  AND deleted_at IS NULL
  AND name = 'Pickman';

-- Pollux (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 182,
  atk = 206,
  def = 176,
  updated_at = NOW()
WHERE id = 43
  AND deleted_at IS NULL
  AND name = 'Pollux';

-- Ramona (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 156,
  atk = 156,
  def = 156,
  updated_at = NOW()
WHERE id = 44
  AND deleted_at IS NULL
  AND name = 'Ramona';

-- Ryker (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 234,
  atk = 194,
  def = 188,
  updated_at = NOW()
WHERE id = 45
  AND deleted_at IS NULL
  AND name = 'Ryker';

-- Salvador (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 246,
  atk = 159,
  def = 246,
  updated_at = NOW()
WHERE id = 46
  AND deleted_at IS NULL
  AND name = 'Salvador';

-- Sanga (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 167,
  atk = 130,
  def = 198,
  updated_at = NOW()
WHERE id = 47
  AND deleted_at IS NULL
  AND name = 'Sanga';

-- Sorel (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 171,
  atk = 241,
  def = 124,
  updated_at = NOW()
WHERE id = 48
  AND deleted_at IS NULL
  AND name = 'Sorel';

-- Tawil (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 176,
  atk = 176,
  def = 176,
  updated_at = NOW()
WHERE id = 49
  AND deleted_at IS NULL
  AND name = 'Tawil';

-- Thais (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 182,
  atk = 176,
  def = 164,
  updated_at = NOW()
WHERE id = 50
  AND deleted_at IS NULL
  AND name = 'Thais';

-- Tinct (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 136,
  atk = 125,
  def = 130,
  updated_at = NOW()
WHERE id = 51
  AND deleted_at IS NULL
  AND name = 'Tinct';

-- Tulu (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 199,
  atk = 223,
  def = 176,
  updated_at = NOW()
WHERE id = 52
  AND deleted_at IS NULL
  AND name = 'Tulu';

-- Uvhash (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 188,
  atk = 177,
  def = 156,
  updated_at = NOW()
WHERE id = 53
  AND deleted_at IS NULL
  AND name = 'Uvhash';

-- Wanda (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 206,
  atk = 129,
  def = 241,
  updated_at = NOW()
WHERE id = 54
  AND deleted_at IS NULL
  AND name = 'Wanda';

-- Winkle (gnostic lv0, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 146,
  atk = 130,
  def = 167,
  updated_at = NOW()
WHERE id = 55
  AND deleted_at IS NULL
  AND name = 'Winkle';

-- Xu (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 264,
  atk = 159,
  def = 147,
  updated_at = NOW()
WHERE id = 56
  AND deleted_at IS NULL
  AND name = 'Xu';

-- Vortice (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 194,
  atk = 234,
  def = 159,
  updated_at = NOW()
WHERE id = 57
  AND deleted_at IS NULL
  AND name = 'Vortice';

-- Arachne (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 188,
  atk = 136,
  def = 182,
  updated_at = NOW()
WHERE id = 58
  AND deleted_at IS NULL
  AND name = 'Arachne';

-- Saya (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 136,
  atk = 136,
  def = 129,
  updated_at = NOW()
WHERE id = 59
  AND deleted_at IS NULL
  AND name = 'Saya';

-- Pontos (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 234,
  atk = 171,
  def = 229,
  updated_at = NOW()
WHERE id = 174
  AND deleted_at IS NULL
  AND name = 'Pontos';

-- Lotan: Cetarchon (gnostic lv5, soulforge lv10, +30%)
UPDATE public.awakener
SET
  con = 153,
  atk = 264,
  def = 159,
  updated_at = NOW()
WHERE id = 175
  AND deleted_at IS NULL
  AND name = 'Lotan: Cetarchon';
