


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE TYPE "public"."awakener_stat" AS ENUM (
    'con',
    'atk',
    'def',
    'skey',
    'damage_amp',
    'crit_rate',
    'crit_dmg',
    'realm_mastery',
    'aliemus_regen',
    'sigil_yield',
    'death_resist'
);


ALTER TYPE "public"."awakener_stat" OWNER TO "postgres";


CREATE TYPE "public"."curve_type" AS ENUM (
    'linear',
    'exponential',
    'logarithmic'
);


ALTER TYPE "public"."curve_type" OWNER TO "postgres";


CREATE TYPE "public"."operation_type" AS ENUM (
    'add_to_base_value',
    'add_to_multiplier',
    'compound_multiplier',
    'add_hits',
    'subtract'
);


ALTER TYPE "public"."operation_type" OWNER TO "postgres";


CREATE TYPE "public"."realm" AS ENUM (
    'chaos',
    'caro',
    'propagation caro',
    'aequor',
    'divine aequor',
    'ultra',
    'singularity ultra'
);


ALTER TYPE "public"."realm" OWNER TO "postgres";


CREATE TYPE "public"."source_type" AS ENUM (
    'command card',
    'exalt',
    'tentacle',
    'rouse',
    'talent'
);


ALTER TYPE "public"."source_type" OWNER TO "postgres";


CREATE TYPE "public"."source_type_old" AS ENUM (
    'command card',
    'exalt',
    'tentacle',
    'rouse',
    'talent',
    'self'
);


ALTER TYPE "public"."source_type_old" OWNER TO "postgres";


CREATE TYPE "public"."target_type" AS ENUM (
    'self',
    'single',
    'aoe'
);


ALTER TYPE "public"."target_type" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."awakener" (
    "id" integer NOT NULL,
    "name" character varying(255),
    "realm" "public"."realm",
    "con" double precision,
    "atk" double precision,
    "def" double precision,
    "skey" double precision,
    "damage_amp" double precision,
    "crit_rate" double precision,
    "crit_dmg" double precision,
    "realm_mastery" double precision,
    "aliemus_regen" double precision,
    "sigil_yield" double precision,
    "death_resist" double precision,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "deleted_at" timestamp without time zone
);


ALTER TABLE "public"."awakener" OWNER TO "postgres";


ALTER TABLE "public"."awakener" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."awakener_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."awakener_tag_manifestation" (
    "id" integer NOT NULL,
    "awakener_id" integer NOT NULL,
    "tag_id" integer NOT NULL,
    "metadata" "text",
    "value_scalar" double precision,
    "base_hits" integer,
    "required_e" integer,
    "required_realm" "public"."realm",
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "deleted_at" timestamp without time zone,
    "source_type" "public"."source_type",
    "target_type" "public"."target_type",
    "dependency_stat" "public"."awakener_stat",
    "ramp_turns" integer DEFAULT 1,
    "buff_target_type_restriction" "public"."source_type_old",
    "replaces_manifestation_id" integer
);


ALTER TABLE "public"."awakener_tag_manifestation" OWNER TO "postgres";


ALTER TABLE "public"."awakener_tag_manifestation" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."awakener_tag_manifestation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."desire" (
    "id" integer NOT NULL,
    "name" character varying,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "deleted_at" timestamp without time zone
);


ALTER TABLE "public"."desire" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."desire_demand" (
    "id" integer NOT NULL,
    "desire_id" integer NOT NULL,
    "tag_id" integer NOT NULL,
    "base_priority_weight" double precision,
    "target_value" double precision,
    "curve" "public"."curve_type" DEFAULT 'logarithmic'::"public"."curve_type",
    "decay_rate" double precision DEFAULT 1,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "deleted_at" timestamp without time zone
);


ALTER TABLE "public"."desire_demand" OWNER TO "postgres";


COMMENT ON COLUMN "public"."desire_demand"."base_priority_weight" IS 'How much the team wants this at 0% fulfillment';



COMMENT ON COLUMN "public"."desire_demand"."target_value" IS 'The point where fulfillment = 100%';



COMMENT ON COLUMN "public"."desire_demand"."decay_rate" IS 'Controls how aggressively weight drops';



ALTER TABLE "public"."desire_demand" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."desire_demand_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."desire" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."desire_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."manifestation_interaction_override" (
    "id" integer NOT NULL,
    "manifestation_id" integer,
    "modifier_tag_id" integer,
    "override_default_factor" double precision,
    "is_disabled" boolean DEFAULT false,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "deleted_at" timestamp without time zone,
    "math_operation" "public"."operation_type",
    "target_type" "public"."target_type",
    "dependency_stat" "public"."awakener_stat"
);


ALTER TABLE "public"."manifestation_interaction_override" OWNER TO "postgres";


COMMENT ON COLUMN "public"."manifestation_interaction_override"."override_default_factor" IS 'Changes the default math value';



COMMENT ON COLUMN "public"."manifestation_interaction_override"."is_disabled" IS 'If true, completely cuts the synergy link';



ALTER TABLE "public"."manifestation_interaction_override" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."manifestation_interaction_override_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."path" (
    "id" integer NOT NULL,
    "awakener_id" integer NOT NULL,
    "desire_id" integer NOT NULL
);


ALTER TABLE "public"."path" OWNER TO "postgres";


ALTER TABLE "public"."path" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."path_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tag" (
    "id" integer NOT NULL,
    "tag_name" character varying(255) NOT NULL,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "deleted_at" timestamp without time zone
);


ALTER TABLE "public"."tag" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tag_default_interaction" (
    "id" integer NOT NULL,
    "modifier_tag_id" integer,
    "target_tag_id" integer,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "deleted_at" timestamp without time zone,
    "source_type" "public"."source_type",
    "math_operation" "public"."operation_type" DEFAULT 'compound_multiplier'::"public"."operation_type" NOT NULL,
    "default_factor" double precision DEFAULT 1.0,
    "exclusion_suffix" integer
);


ALTER TABLE "public"."tag_default_interaction" OWNER TO "postgres";


COMMENT ON COLUMN "public"."tag_default_interaction"."exclusion_suffix" IS 'The specific branch to cut off';



ALTER TABLE "public"."tag_default_interaction" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tag_default_interaction_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."tag" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tag_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."awakener"
    ADD CONSTRAINT "awakener_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."awakener"
    ADD CONSTRAINT "awakener_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."awakener_tag_manifestation"
    ADD CONSTRAINT "awakener_tag_manifestation_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."desire_demand"
    ADD CONSTRAINT "desire_demand_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."desire"
    ADD CONSTRAINT "desire_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."manifestation_interaction_override"
    ADD CONSTRAINT "manifestation_interaction_override_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."path"
    ADD CONSTRAINT "path_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tag_default_interaction"
    ADD CONSTRAINT "tag_default_interaction_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tag"
    ADD CONSTRAINT "tag_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tag"
    ADD CONSTRAINT "tag_tag_name_key" UNIQUE ("tag_name");



CREATE UNIQUE INDEX "tag_default_interaction_modifier_target_source_active_uniq" ON "public"."tag_default_interaction" USING "btree" ("modifier_tag_id", "target_tag_id", "source_type") WHERE ("deleted_at" IS NULL);



ALTER TABLE ONLY "public"."awakener_tag_manifestation"
    ADD CONSTRAINT "awakener_tag_manifestation_awakener_id_fkey" FOREIGN KEY ("awakener_id") REFERENCES "public"."awakener"("id") DEFERRABLE;



ALTER TABLE ONLY "public"."awakener_tag_manifestation"
    ADD CONSTRAINT "awakener_tag_manifestation_replaces_manifestation_id_fkey" FOREIGN KEY ("replaces_manifestation_id") REFERENCES "public"."awakener_tag_manifestation"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."awakener_tag_manifestation"
    ADD CONSTRAINT "awakener_tag_manifestation_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tag"("id") DEFERRABLE;



ALTER TABLE ONLY "public"."desire_demand"
    ADD CONSTRAINT "desire_demand_desire_id_fkey" FOREIGN KEY ("desire_id") REFERENCES "public"."desire"("id") DEFERRABLE;



ALTER TABLE ONLY "public"."desire_demand"
    ADD CONSTRAINT "desire_demand_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tag"("id") DEFERRABLE;



ALTER TABLE ONLY "public"."manifestation_interaction_override"
    ADD CONSTRAINT "manifestation_interaction_override_manifestation_id_fkey" FOREIGN KEY ("manifestation_id") REFERENCES "public"."awakener_tag_manifestation"("id") DEFERRABLE;



ALTER TABLE ONLY "public"."manifestation_interaction_override"
    ADD CONSTRAINT "manifestation_interaction_override_modifier_tag_id_fkey" FOREIGN KEY ("modifier_tag_id") REFERENCES "public"."tag"("id") DEFERRABLE;



ALTER TABLE ONLY "public"."path"
    ADD CONSTRAINT "path_awakener_id_fkey" FOREIGN KEY ("awakener_id") REFERENCES "public"."awakener"("id") DEFERRABLE;



ALTER TABLE ONLY "public"."path"
    ADD CONSTRAINT "path_desire_id_fkey" FOREIGN KEY ("desire_id") REFERENCES "public"."desire"("id") DEFERRABLE;



ALTER TABLE ONLY "public"."tag_default_interaction"
    ADD CONSTRAINT "tag_default_interaction_exclusion_suffix_fkey" FOREIGN KEY ("exclusion_suffix") REFERENCES "public"."tag"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."tag_default_interaction"
    ADD CONSTRAINT "tag_default_interaction_modifier_tag_id_fkey" FOREIGN KEY ("modifier_tag_id") REFERENCES "public"."tag"("id") DEFERRABLE;



ALTER TABLE ONLY "public"."tag_default_interaction"
    ADD CONSTRAINT "tag_default_interaction_target_tag_id_fkey" FOREIGN KEY ("target_tag_id") REFERENCES "public"."tag"("id") DEFERRABLE;



ALTER TABLE "public"."awakener" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."awakener_tag_manifestation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."desire" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."desire_demand" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."manifestation_interaction_override" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."path" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tag" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tag_default_interaction" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."awakener" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."awakener" TO "authenticated";
GRANT ALL ON TABLE "public"."awakener" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."awakener_tag_manifestation" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."awakener_tag_manifestation" TO "authenticated";
GRANT ALL ON TABLE "public"."awakener_tag_manifestation" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."desire" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."desire" TO "authenticated";
GRANT ALL ON TABLE "public"."desire" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."desire_demand" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."desire_demand" TO "authenticated";
GRANT ALL ON TABLE "public"."desire_demand" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."manifestation_interaction_override" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."manifestation_interaction_override" TO "authenticated";
GRANT ALL ON TABLE "public"."manifestation_interaction_override" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."path" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."path" TO "authenticated";
GRANT ALL ON TABLE "public"."path" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."tag" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."tag" TO "authenticated";
GRANT ALL ON TABLE "public"."tag" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."tag_default_interaction" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."tag_default_interaction" TO "authenticated";
GRANT ALL ON TABLE "public"."tag_default_interaction" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";







