-- Phase 3a.3: instance_count / base_copies + copy_provider_group

-- 1. Rename base_hits → instance_count, backfill nulls, NOT NULL DEFAULT 1
ALTER TABLE public.awakener_tag_manifestation
  RENAME COLUMN base_hits TO instance_count;

UPDATE public.awakener_tag_manifestation
SET instance_count = 1
WHERE instance_count IS NULL;

ALTER TABLE public.awakener_tag_manifestation
  ALTER COLUMN instance_count SET DEFAULT 1,
  ALTER COLUMN instance_count SET NOT NULL;

-- 2. base_copies
ALTER TABLE public.awakener_tag_manifestation
  ADD COLUMN base_copies integer NOT NULL DEFAULT 1;

-- 3. copy_provider_group
CREATE TABLE public.copy_provider_group (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone
);

ALTER TABLE public.copy_provider_group OWNER TO postgres;

CREATE UNIQUE INDEX copy_provider_group_name_active_uniq
  ON public.copy_provider_group USING btree (name)
  WHERE (deleted_at IS NULL);

ALTER TABLE public.copy_provider_group ENABLE ROW LEVEL SECURITY;

GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.copy_provider_group TO anon;
GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.copy_provider_group TO authenticated;
GRANT ALL ON TABLE public.copy_provider_group TO service_role;

-- 4. copy_provider_group_member
CREATE TABLE public.copy_provider_group_member (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id integer NOT NULL,
  tag_id integer NOT NULL,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone
);

ALTER TABLE public.copy_provider_group_member OWNER TO postgres;

ALTER TABLE ONLY public.copy_provider_group_member
  ADD CONSTRAINT copy_provider_group_member_group_id_fkey
  FOREIGN KEY (group_id) REFERENCES public.copy_provider_group (id) DEFERRABLE;

ALTER TABLE ONLY public.copy_provider_group_member
  ADD CONSTRAINT copy_provider_group_member_tag_id_fkey
  FOREIGN KEY (tag_id) REFERENCES public.tag (id) DEFERRABLE;

CREATE UNIQUE INDEX copy_provider_group_member_group_tag_active_uniq
  ON public.copy_provider_group_member USING btree (group_id, tag_id)
  WHERE (deleted_at IS NULL);

ALTER TABLE public.copy_provider_group_member ENABLE ROW LEVEL SECURITY;

GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.copy_provider_group_member TO anon;
GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.copy_provider_group_member TO authenticated;
GRANT ALL ON TABLE public.copy_provider_group_member TO service_role;

-- 5. ATM FK
ALTER TABLE public.awakener_tag_manifestation
  ADD COLUMN copy_provider_group_id integer NULL;

ALTER TABLE ONLY public.awakener_tag_manifestation
  ADD CONSTRAINT awakener_tag_manifestation_copy_provider_group_id_fkey
  FOREIGN KEY (copy_provider_group_id) REFERENCES public.copy_provider_group (id) DEFERRABLE;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
