CREATE TABLE public.realm_tag_manifestation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  realm_id integer NOT NULL,
  tag_id integer NOT NULL,
  metadata text,
  value_scalar double precision,
  is_accumulating boolean NOT NULL DEFAULT false,
  is_permanent boolean DEFAULT false,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone
);

ALTER TABLE public.realm_tag_manifestation OWNER TO postgres;

ALTER TABLE ONLY public.realm_tag_manifestation
  ADD CONSTRAINT realm_tag_manifestation_realm_id_fkey
  FOREIGN KEY (realm_id) REFERENCES public.realm (id) DEFERRABLE;

ALTER TABLE ONLY public.realm_tag_manifestation
  ADD CONSTRAINT realm_tag_manifestation_tag_id_fkey
  FOREIGN KEY (tag_id) REFERENCES public.tag (id) DEFERRABLE;

ALTER TABLE public.realm_tag_manifestation ENABLE ROW LEVEL SECURITY;

GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.realm_tag_manifestation TO anon;
GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.realm_tag_manifestation TO authenticated;
GRANT ALL ON TABLE public.realm_tag_manifestation TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
