-- Replace realm enum with realm lookup table.
-- Postgres cannot have a type and table both named realm, so rename the enum first.

ALTER TYPE public.realm RENAME TO realm_enum_obsolete;

CREATE TABLE public.realm (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone,
  "replace" integer
);

ALTER TABLE public.realm OWNER TO postgres;

ALTER TABLE ONLY public.realm
  ADD CONSTRAINT realm_name_key UNIQUE (name);

ALTER TABLE ONLY public.realm
  ADD CONSTRAINT realm_replace_fkey
  FOREIGN KEY ("replace") REFERENCES public.realm (id);

INSERT INTO public.realm (name, created_at, updated_at)
SELECT unnest(enum_range(NULL::public.realm_enum_obsolete)::text[]), now(), now();

-- awakener.realm
ALTER TABLE public.awakener ADD COLUMN realm_new integer;
UPDATE public.awakener a
SET realm_new = r.id
FROM public.realm r
WHERE a.realm::text = r.name;
ALTER TABLE public.awakener DROP COLUMN realm;
ALTER TABLE public.awakener RENAME COLUMN realm_new TO realm;
ALTER TABLE ONLY public.awakener
  ADD CONSTRAINT awakener_realm_fkey
  FOREIGN KEY (realm) REFERENCES public.realm (id);

-- awakener_tag_manifestation.required_realm
ALTER TABLE public.awakener_tag_manifestation ADD COLUMN required_realm_new integer;
UPDATE public.awakener_tag_manifestation m
SET required_realm_new = r.id
FROM public.realm r
WHERE m.required_realm::text = r.name;
ALTER TABLE public.awakener_tag_manifestation DROP COLUMN required_realm;
ALTER TABLE public.awakener_tag_manifestation RENAME COLUMN required_realm_new TO required_realm;
ALTER TABLE ONLY public.awakener_tag_manifestation
  ADD CONSTRAINT awakener_tag_manifestation_required_realm_fkey
  FOREIGN KEY (required_realm) REFERENCES public.realm (id);

-- posse_tag_manifestation.required_realm
ALTER TABLE public.posse_tag_manifestation ADD COLUMN required_realm_new integer;
UPDATE public.posse_tag_manifestation m
SET required_realm_new = r.id
FROM public.realm r
WHERE m.required_realm::text = r.name;
ALTER TABLE public.posse_tag_manifestation DROP COLUMN required_realm;
ALTER TABLE public.posse_tag_manifestation RENAME COLUMN required_realm_new TO required_realm;
ALTER TABLE ONLY public.posse_tag_manifestation
  ADD CONSTRAINT posse_tag_manifestation_required_realm_fkey
  FOREIGN KEY (required_realm) REFERENCES public.realm (id);

-- wheel_tag_manifestation.required_realm
ALTER TABLE public.wheel_tag_manifestation ADD COLUMN required_realm_new integer;
UPDATE public.wheel_tag_manifestation m
SET required_realm_new = r.id
FROM public.realm r
WHERE m.required_realm::text = r.name;
ALTER TABLE public.wheel_tag_manifestation DROP COLUMN required_realm;
ALTER TABLE public.wheel_tag_manifestation RENAME COLUMN required_realm_new TO required_realm;
ALTER TABLE ONLY public.wheel_tag_manifestation
  ADD CONSTRAINT wheel_tag_manifestation_required_realm_fkey
  FOREIGN KEY (required_realm) REFERENCES public.realm (id);

-- covenant_tag_manifestation.required_realm1
ALTER TABLE public.covenant_tag_manifestation ADD COLUMN required_realm1_new integer;
UPDATE public.covenant_tag_manifestation m
SET required_realm1_new = r.id
FROM public.realm r
WHERE m.required_realm1::text = r.name;
ALTER TABLE public.covenant_tag_manifestation DROP COLUMN required_realm1;
ALTER TABLE public.covenant_tag_manifestation RENAME COLUMN required_realm1_new TO required_realm1;
ALTER TABLE ONLY public.covenant_tag_manifestation
  ADD CONSTRAINT covenant_tag_manifestation_required_realm1_fkey
  FOREIGN KEY (required_realm1) REFERENCES public.realm (id);

-- covenant_tag_manifestation.required_realm2
ALTER TABLE public.covenant_tag_manifestation ADD COLUMN required_realm2_new integer;
UPDATE public.covenant_tag_manifestation m
SET required_realm2_new = r.id
FROM public.realm r
WHERE m.required_realm2::text = r.name;
ALTER TABLE public.covenant_tag_manifestation DROP COLUMN required_realm2;
ALTER TABLE public.covenant_tag_manifestation RENAME COLUMN required_realm2_new TO required_realm2;
ALTER TABLE ONLY public.covenant_tag_manifestation
  ADD CONSTRAINT covenant_tag_manifestation_required_realm2_fkey
  FOREIGN KEY (required_realm2) REFERENCES public.realm (id);

ALTER TABLE public.realm ENABLE ROW LEVEL SECURITY;

GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.realm TO anon;
GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.realm TO authenticated;
GRANT ALL ON TABLE public.realm TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
