-- Relic–tag pairings. Mirrors posse_tag_manifestation with a reduced column set.

CREATE TABLE public.relic_tag_manifestation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relic_id integer NOT NULL,
  tag_id integer NOT NULL,
  value_scalar double precision,
  target_type target_type,
  metadata text,
  is_accumulating boolean NOT NULL DEFAULT false,
  is_permanent boolean,
  required_realm integer,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  deleted_at timestamp without time zone
);

ALTER TABLE public.relic_tag_manifestation OWNER TO postgres;

ALTER TABLE ONLY public.relic_tag_manifestation
  ADD CONSTRAINT relic_tag_manifestation_relic_id_fkey
  FOREIGN KEY (relic_id) REFERENCES public.relic (id) ON DELETE CASCADE;

ALTER TABLE ONLY public.relic_tag_manifestation
  ADD CONSTRAINT relic_tag_manifestation_tag_id_fkey
  FOREIGN KEY (tag_id) REFERENCES public.tag (id);

ALTER TABLE ONLY public.relic_tag_manifestation
  ADD CONSTRAINT relic_tag_manifestation_required_realm_fkey
  FOREIGN KEY (required_realm) REFERENCES public.realm (id);

ALTER TABLE public.relic_tag_manifestation ENABLE ROW LEVEL SECURITY;

GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.relic_tag_manifestation TO anon;
GRANT REFERENCES, TRIGGER, TRUNCATE, MAINTAIN ON TABLE public.relic_tag_manifestation TO authenticated;
GRANT ALL ON TABLE public.relic_tag_manifestation TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE POLICY anon_select_alive ON public.relic_tag_manifestation
  FOR SELECT TO anon
  USING (deleted_at IS NULL);
