-- Damage-relevance mirror (Relic Picker performance).
--
-- `is_damage_relevant` is a DERIVED, team-independent flag: true when a tag can
-- reach one of the six Total Damage channels via tag_default_interaction, or is
-- one of the code-driven synthetic seeds in
-- src/lib/path-carver/damage-relevance.ts.
--
-- It is NOT read at runtime. The Relic Picker computes the per-team closure in
-- code (the closure depends on which manifestations/interactions are present,
-- and covers runtime-only synthetic ids that have no tag row). This column is a
-- generated mirror for SQL/admin inspection and drift checks, populated by
-- scripts/sync-tag-damage-relevance.ts.
ALTER TABLE public.tag
  ADD COLUMN IF NOT EXISTS is_damage_relevant boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.tag.is_damage_relevant IS
  'Derived (not runtime): true when this tag can reach a Total Damage channel via tag_default_interaction or a code synthetic seed. Generated by scripts/sync-tag-damage-relevance.ts; see src/lib/path-carver/damage-relevance.ts.';

ALTER TABLE public.tag
  ADD COLUMN IF NOT EXISTS damage_relevance_reason text;

COMMENT ON COLUMN public.tag.damage_relevance_reason IS
  'Audit note for is_damage_relevant: ''seed'' for a code synthetic seed, ''graph'' for interaction-graph reachability.';
